[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
maryjane_confidential = "DGcYT9EVrrwMGEnUcYiPUhrfzvGBjNFZ7t619BWWPn99"

[programs.devnet]
maryjane_confidential = "DGcYT9EVrrwMGEnUcYiPUhrfzvGBjNFZ7t619BWWPn99"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[hooks]
