[toolchain]
anchor_version = "1.2.0"
solana_version = "3.1.10"

[features]
resolution = false
skip-lint = false

[programs.localnet]
milady_market = "HriJWSipKzjya2ScJ8f2AyVwrkbugLtmVELwvb2w7vRL"

[programs.devnet]
milady_market = "HriJWSipKzjya2ScJ8f2AyVwrkbugLtmVELwvb2w7vRL"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec tsx tests/math.spec.ts"
